job/urls.py
from django.urls import path
from job import views

app_name = 'job'


urlpatterns = [
    path('', views.index, name='home'),
    path('post/listing/', views.post_listing, name='post-listing-all'),
    path('post/listing/<str:slug>/', views.post_listing, name='post-listing'),
    path('post/detail/<str:slug>/', views.post_detail, name='post-detail'),

    path('post/job-add/', views.add_job, name='add-job'),
    path('post/job-add/<str:slug>/', views.add_job, name='update-job'),
    path('company-add/', views.add_company, name='add-company'),
    path('company-add/<int:pk>/', views.add_company, name='update-company'),
    path('company-detail/', views.company_detail, name='company-detail'),

    path('job-apply/<str:slug>/', views.apply_job, name='job-apply'),
    path('application-detail/<str:slug>/', views.application_detail, name='application-detail'),
    path('select-candidate/<str:slug>/<int:pk>/', views.select_candidate, name='select-candidate'),
]

job_seeker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('job.urls', namespace='job')),
    path('user/', include('user.urls', namespace='user')),
    path('admin/', admin.site.urls),
    path('contact/', TemplateView.as_view(template_name='contact.html'), name='contact'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from user.models import Profile
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver


JOB_TIME = (
    ('Part Time', 'Part Time'),
    ('Full Time', 'Full Time'),
)
SALARY_TYPE = (
    ('yearly', 'Yearly'),
    ('monthly', 'Monthly'),
)


class Category(models.Model):
    category_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True)
    logo = models.CharField(max_length=50, default='tour')
    created_at = models.DateField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.category_name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.category_name


@receiver(post_save, sender=Profile)
def save_profile(sender, instance, created, *args, **kwargs):
    if instance.is_company:
        c = Company(profile=instance)
        c.save()
    if not instance.is_company:
        instance.company_set.all().delete()

class Company(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=200)
    description = models.TextField()
    web = models.URLField(null=True, blank=True)
    email = models.EmailField()

    def __str__(self):
        return f"{self.profile} - {self.company_name}"


class Job(models.Model):
    job_name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='job', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='jobs')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='jobs')
    location = models.CharField(max_length=200)
    vacancy = models.IntegerField(default=1)
    job_time = models.CharField(choices=JOB_TIME, max_length=10)
    salary_type = models.CharField(choices=SALARY_TYPE, max_length=10)
    max_salary = models.DecimalField(decimal_places=2, max_digits=6)
    min_salary = models.DecimalField(decimal_places=2, max_digits=6)
    last_date = models.DateField(default=timezone.now())
    posted_date = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['-posted_date']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.job_name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.job_name


class Application(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='applications')
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    selected = models.BooleanField(default=False)
    apply_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.job.job_name} - {self.profile.user.username}'

@receiver(pre_save, sender=Application)
def _post_save_receiver(sender, instance,  **kwargs):
    job = Job.objects.get(pk=instance.job.pk)
    if instance.selected:
        if job.vacancy > 0:
            job.vacancy -= 1
            job.save()
        else:
            instance.selected = False

job/forms.py
from user.models import Profile
from django import forms
from job.models import Job, Company


class JobForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super ().__init__(*args,**kwargs)
        self.fields['company'].queryset = Company.objects.filter(profile=self.request.user.profile)

    class Meta:
        model = Job
        fields = '__all__'
        exclude = ('slug', )

        widgets = {
            'job_name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'vacancy': forms.TextInput(attrs={'class': 'form-control'}),
            'max_salary': forms.TextInput(attrs={'class': 'form-control'}),
            'min_salary': forms.TextInput(attrs={'class': 'form-control'}),
            'last_date': forms.TextInput(attrs={'class': 'form-control'}),
        }
    
class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'
        exclude = ('profile', )

        widgets = {
            'company_name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'web': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
        }

job/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from job.models import Category, Company, Job, Application
from job.decorators import *
from job.forms import JobForm, CompanyForm
from user.models import Profile
from urllib.parse import quote


def index(request):
    category_qs = Category.objects.all()
    jobs = Job.objects.all()[:4]
    context = {
        'categories': category_qs,
        'jobs': jobs,
    }
    return render(request, 'index.html', context)


@allow_user
def post_listing(request, slug=None):
    if slug:
        jobs = Job.objects.filter(category__slug=slug)
    else:
        jobs = Job.objects.all()
    context = {
        'jobs': jobs,
    }
    return render(request, 'job/job_listing.html', context)


@login_required
@allow_user
def post_detail(request, slug):
    job = Job.objects.filter(slug=slug).first()
    applications = Application.objects.filter(job=job, profile=request.user.profile)
    applied = True if applications.exists() else False
    context = {
        'job': job,
        'applied': applied,
    }
    return render(request, 'job/job_details.html', context)


@login_required
@allow_company
def add_job(request, slug=None):
    if slug:
        job = Job.objects.get(slug=slug)
        form = JobForm(request.POST or None, request.FILES or None, instance=job, request=request)
    else:
        form = JobForm(request.POST or None, request.FILES or None, request=request)
    jobs = Job.objects.filter(company__profile=request.user.profile)
    if request.method == "POST":
	    if form.is_valid():
		    form.save()
		    return redirect("job:add-job")
    context = {
        'form': form,
        'jobs': jobs,
    }
    return render(request, 'job/add_job.html', context)


@login_required
@allow_company
def add_company(request, pk=None):
    if pk:
        company = Company.objects.get(pk=pk)
        form = CompanyForm(request.POST or None, request.FILES or None, instance=company)
    else:
        form = CompanyForm(request.POST or None, request.FILES or None)
    companies = request.user.profile.company_set.all()
    if request.method == "POST":
        if form.is_valid():
            company = form.save(commit=False)
            company.profile = request.user.profile
            company.save()
            return redirect("job:add-company")
    context = {
        'form': form,
        'companies': companies,
    }
    return render(request, 'job/add_company.html', context)


@login_required
@allow_company
def company_detail(request):
    profile = Profile.objects.get(user=request.user)
    companies = Company.objects.filter(profile=profile)
    context = {
        'companies': companies,
        'profile': profile,
    }
    return render(request, 'job/company_details.html', context)


@login_required
@allow_company
def application_detail(request, slug):
    job = Job.objects.filter(slug=slug).first()
    applications = job.applications.all()
    context = {
        'job': job,
        'applications': applications,
    }
    return render(request, 'job/application_details.html', context)


@login_required
@allow_company
def select_candidate(request, slug, pk):
    try:
        application = Application.objects.get(pk=pk)
    except:
        return redirect('job:home') 
    if not application.selected:
        application.selected = True
        application.save()
    return redirect('job:application-detail', slug=slug)
    


@login_required
@allow_user
def apply_job(request, slug):
    current_url = quote(request.get_full_path())
    try:
        job = Job.objects.get(slug=slug)
    except:
        return redirect('job:home') 
    profile = Profile.objects.get(user=request.user)
    if profile.resume:
        if job.vacancy > 0:
            app, _ = Application.objects.get_or_create(job=job, profile=request.user.profile)
        else:
            messages.error(request, " There is no vacancy available.")
            return redirect('job:post-listing-all')
    else:
        messages.error(request, " You don't have a resume first upload resume and then apply for this job.")
        return redirect(reverse('user:profile') + f'?next={current_url}')
    return redirect('job:post-detail', slug=slug)

job/templates/job/add_company.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Hero Area Start-->
<div class="slider-area ">
    <div class="single-slider section-overly slider-height2 d-flex align-items-center"
        data-background="{% static 'img/hero/about.jpg'%}">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>Add a Company</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Hero Area End -->

<!--================Login Box Area =================-->
<section class="contact-section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="contact-title">{{ "fill in job details."|title }}</h2>
            </div>
            <div class="col-lg-7">
                <form class="form-contact contact_form" action=" " method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <table cellpadding=10 class='table'>
                            {{ form.as_table }}
                        </table>
                    </div>
                    <div class="form-group mt-3">
                        <button type="submit" class="button button-contactForm boxed-btn">Save</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-4 offset-lg-1">
                <div class="card mt-3">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-center align-items-center flex-wrap">
                            <h3 class="mb-1">
                                <svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><title>bank-buidling-flat</title><path d="M256,510.4C116.1,510.4,2.28,396.28,2.28,256S116.1,1.6,256,1.6,509.72,115.73,509.72,256,395.9,510.4,256,510.4Z" fill="none" stroke="#131313" stroke-miterlimit="10" stroke-width="4.56"/><ellipse cx="256" cy="256" rx="217.71" ry="218.3" fill="#131313"/><path d="M338.45,343.59c0-.19.07-.36.07-.56V337.4c0-4-4.22-7.22-9.69-7.71V218.89H299.2V329.6H272.3V218.89H242.65V329.6H215.74V218.89H186.09V329.66c-5.75.28-10.26,3.61-10.26,7.74V343a6.33,6.33,0,0,0,.19,1.5c-3.22,1.51-5.36,4.09-5.36,7v6.11c0,4.67,5.35,8.43,11.93,8.43H334.68c6.58,0,11.91-3.76,11.91-8.43v-6.11C346.6,347.85,343.2,344.71,338.45,343.59Z" fill="#ede9e2"/><path d="M346.22,195.56,321.1,180.42l-26.66-16.08-25.1-15.14c-7.33-4.42-19.34-4.42-26.66,0l-25.1,15.14-26.66,16.08-25.13,15.14c-7.33,4.42-6.33,8,2.24,8h18.07v10.12h29.65V203.59h26.91v10.12H272.3V203.59H299.2v10.12h29.63V203.59H344C352.55,203.59,353.54,200,346.22,195.56Zm-90.66-33a12.95,12.95,0,1,1-12.91,12.95A12.92,12.92,0,0,1,255.56,162.52Z" fill="#ede9e2"/></svg>
                                Companies
                            </h3>
                        </li>
                        {% for company in companies %}
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <p class="text-secondary">
                                    <a href="{% url 'job:update-company' company.pk %}">{{ company.company_name }}: </a>
                                </p>
                                <span class="text-secondary">{{ company.email }}</span>
                            </li>
                        {% empty %}
                            <span class="text-secondary">None</span>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
<!--================End Login Box Area =================-->
{% endblock content %}

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Hero Area Start-->
<div class="slider-area ">
    <div class="single-slider section-overly slider-height2 d-flex align-items-center"
        data-background="{% static 'img/hero/about.jpg'%}">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>Add a job</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Hero Area End -->

<!--================Login Box Area =================-->
<section class="contact-section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="contact-title">{{ "fill in job details."|title }}</h2>
            </div>
            <div class="col-lg-7">
                <form class="form-contact contact_form" action=" " method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <table cellpadding=10 class='table'>
                            {{ form.as_table }}
                        </table>
                    </div>
                    <div class="form-group mt-3">
                        <button type="submit" class="button button-contactForm boxed-btn">Save</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-4 offset-lg-1">
                <div class="card mt-3">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-center align-items-center flex-wrap">
                            <h3 class="mb-1">
                                <svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><title>bank-buidling-flat</title><path d="M256,510.4C116.1,510.4,2.28,396.28,2.28,256S116.1,1.6,256,1.6,509.72,115.73,509.72,256,395.9,510.4,256,510.4Z" fill="none" stroke="#131313" stroke-miterlimit="10" stroke-width="4.56"/><ellipse cx="256" cy="256" rx="217.71" ry="218.3" fill="#131313"/><path d="M338.45,343.59c0-.19.07-.36.07-.56V337.4c0-4-4.22-7.22-9.69-7.71V218.89H299.2V329.6H272.3V218.89H242.65V329.6H215.74V218.89H186.09V329.66c-5.75.28-10.26,3.61-10.26,7.74V343a6.33,6.33,0,0,0,.19,1.5c-3.22,1.51-5.36,4.09-5.36,7v6.11c0,4.67,5.35,8.43,11.93,8.43H334.68c6.58,0,11.91-3.76,11.91-8.43v-6.11C346.6,347.85,343.2,344.71,338.45,343.59Z" fill="#ede9e2"/><path d="M346.22,195.56,321.1,180.42l-26.66-16.08-25.1-15.14c-7.33-4.42-19.34-4.42-26.66,0l-25.1,15.14-26.66,16.08-25.13,15.14c-7.33,4.42-6.33,8,2.24,8h18.07v10.12h29.65V203.59h26.91v10.12H272.3V203.59H299.2v10.12h29.63V203.59H344C352.55,203.59,353.54,200,346.22,195.56Zm-90.66-33a12.95,12.95,0,1,1-12.91,12.95A12.92,12.92,0,0,1,255.56,162.52Z" fill="#ede9e2"/></svg>
                                Jobs
                            </h3>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <span class="text-dark h6">Company Name </span>
                            <span class="text-dark h6">Job Name<span>
                        </li>
                        {% for job in jobs %}
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <span class="text-secondary">{{ job.company.company_name }}: </span>
                                <span class="text-secondary">
                                    <a href="{% url 'job:update-job' job.slug %}">{{ job.job_name }}</a>
                                <span>
                            </li>
                        {% empty %}
                            <span class="text-secondary">None</span>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
<!--================End Login Box Area =================-->
{% endblock content %}

job/templates/job/application_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main>

        <!-- Hero Area Start-->
        <div class="slider-area ">
        <div class="single-slider section-overly slider-height2 d-flex align-items-center" data-background="{% static 'img/hero/about.jpg'%}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2>{{ job.job_name|title }}</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
        <!-- Hero Area End -->
        <!-- job post company Start -->
        <div class="job-post-company pt-120 pb-120">
            <div class="container">
                <div class="row justify-content-between">
                    <!-- Left Content -->
                    <div class="col-xl-7 col-lg-8">
                        <!-- job single -->
                        <div class="single-job-items mb-50">
                            <div class="job-items">
                                <div class="company-img">
                                    <a href="{% url 'job:post-detail' job.slug %}"><img src="{% static 'img/icon/job-list1.png'%}" alt=""></a>
                                </div>
                                <div class="job-tittle job-tittle2">
                                    <a href="{% url 'job:post-detail' job.slug %}">
                                        <h4>{{ job.job_name|title }}</h4>
                                    </a>
                                    <ul>
                                        <li>{{ job.category.category_name|title }}</li>
                                        <li><i class="fas fa-map-marker-alt"></i>{{ job.location }}</li>
                                        <li>${{ job.min_salary}} - ${{ job.max_salary }}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                          <!-- job single End -->
                       
                        <div class="job-post-details">
                            <div class="post-details1 mb-50">
                                <!-- Small Section Tittle -->
                                <div class="small-section-tittle">
                                    <h4>{{ applications|length }} Applicant{{ applications|pluralize }} </h4>
                                </div>
                                <div class="">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Username</th>
                                                <th scope="col">Selected</th>
                                                <th scope="col">resume</th>
                                                <th scope="col"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for application in applications %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td>{{ application.profile.user.username }}</td>
                                                <td>{{ application.selected|yesno:"Yeah,No,maybe" }}</td>
                                                <td><a href="{{ application.profile.resume.url }}">View</a></td>
                                                <td><a href="{% url 'job:select-candidate' job.slug application.id %}" class="genric-btn primary-border circle {% if application.selected %}disable{% endif %}">
                                                        Select
                                                </a></td>
                                            </tr>
                                            {% empty %}
                                            <tr>
                                                <td colspan="7" class="text-center">None</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- Right Content -->
                    <div class="col-xl-4 col-lg-4">
                        <div class="post-details3  mb-50">
                            <!-- Small Section Tittle -->
                           <div class="small-section-tittle">
                               <h4>Job Overview</h4>
                           </div>
                          <ul>
                              <li>Posted date : <span>{{ job.posted_date|date:'d M Y'}}</span></li>
                              <li>Location : <span>{{ job.location }}</span></li>
                              <li>Vacancy : <span>{{ job.vacancy }}</span></li>
                              <li>Job nature : <span>{{ job.job_time }}</span></li>
                              <li>Salary :  <span>${{ job.min_salary }} - {{ job.max_salary }} {{ job.salary_type|title }}</span></li>
                              <li>Last date : <span>{{ job.last_date|date:'d M Y'}}</span></li>
                              <li>Time Left : <span>{{ job.posted_date|timesince:job.last_date }}</span></li>
                          </ul>
                        </div>
                        <div class="post-details4  mb-50">
                            <!-- Small Section Tittle -->
                           <div class="small-section-tittle">
                               <h4>Company Information</h4>
                           </div>
                              <span>{{ job.company.company_name }}</span>
                              <p>
                                {{ job.company.description }}
                              </p>
                            <ul>
                                <li>Name: <span>{{ job.company.company_name }} </span></li>
                                <li>Web : <span> {{ job.company.web }}</span></li>
                                <li>Email: <span>{{ job.company.email }}</span></li>
                            </ul>
                       </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- job post company End -->

    </main>
{% endblock content %}

job/templates/job/company_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>

    <!-- Hero Area Start-->
    <div class="slider-area ">
        <div class="single-slider section-overly slider-height2 d-flex align-items-center"
            data-background="{% static 'img/hero/about.jpg'%}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2>Applications</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Hero Area End -->
    <!-- job post company Start -->
    <div class="job-post-company pt-120 pb-120">
        <div class="container">
            <div class="row justify-content-between">
                <!-- Left Content -->
                <div class="col-xl-12 col-lg-12">
                    <!-- job single -->
                    <div class="single-job-items mb-50">
                        <div class="job-items">
                            <div class="company-img company-img-details">
                                <a href="#"><img class="rounded" src="{{ profile.profile_image.url }}" alt=""
                                        style="height: 100px; width:auto;"></a>
                            </div>
                            <div class="job-tittle">
                                <a href="#">
                                    <h4>{{ profile.user.username }}</h4>
                                </a>
                                <ul>
                                    <li>Company: {{ profile.company_set.count }}</li>
                                    <li><i class="fas fa-map-marker-alt"></i>{{ profile.address }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- job single End -->

                </div>
            </div>
            <!-- Right Content -->
            {% for company in companies %}
            <div class="col-xl-12 col-lg-12">
                <div class="post-details3  mb-50">
                        <div class="col col-md-12">
                            <div class="post-details4  mb-50">
                                <!-- Small Section Tittle -->
                                <div class="small-section-tittle">
                                    <h4>Company Information</h4>
                                </div>
                                <ul>
                                    <li>Name: <span>{{ company.company_name }} </span></li>
                                    <li>Web : <span> {{ company.web }}</span></li>
                                    <li>Email: <span>{{ company.email }}</span></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Small Section Tittle -->
                        <hr>
                        <div class="row">
                            <div class="col col-md-12 pt-5">
                                <div class="small-section-tittle">
                                    <h4>Job Overview</h4>
                                </div>
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th scope="col">Job Name</th>
                                            <th scope="col">Posted date</th>
                                            <th scope="col">Location</th>
                                            <th scope="col">Time Left</th>
                                            <th scope="col">Vacancy</th>
                                            <th scope="col">No of applicant</th>
                                            <th scope="col"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for job in company.jobs.all %}
                                        <tr>
                                            <td>{{ job.job_name }}</td>
                                            <td>{{ job.posted_date|date:'d M Y'}}</td>
                                            <td>{{ job.location }}</td>
                                            <td>{{ job.posted_date|timesince:job.last_date }}</td>
                                            <td>{{ job.vacancy }}</td>
                                            <td>{{ job.applications.count }}</td>
                                            <td><a href="{% url 'job:application-detail' job.slug %}" class="genric-btn danger-border circle">See more</a></td>
                                        </tr>
                                        {% empty %}
                                        <tr>
                                            <td colspan="7" class="text-center">None</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <ul>
                                </ul>
                                <div class="apply-btn2">
                                </div>
                            </div>
                    </div>
                </div>
            </div>
            <hr>
            {% endfor %}
        </div>
    </div>
    <!-- job post company End -->
    
</main>
{% endblock content %}